In [10]:
import pandas as pd
df = pd.read_csv(r"C:\Users\kbhunia\Downloads\GDrive Backup Downloads\Jupyter Notebook Programs\excel read files\Sample Data Safety.csv")
df

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,1-Jan-20,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,$0,Wed,1,2020
1,3-Jan-20,NaN,Male,35-49,Vehicle,0.5,Alabama,Lost Time,Day,Fabrication,"$3,367",Fri,1,2020
2,3-Jan-20,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,$0,Fri,1,2020
3,4-Jan-20,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,$0,Sat,1,2020
4,7-Jan-20,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,$0,Tue,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,26-Jun-22,Head,Female,25-34,Crush & Pinch,0.0,California,First Aid,Night,Administration,77,Sun,6,2022
510,27-Jun-22,Hands,Male,25-34,Lifting,0.0,Florida,Near Miss,Afternoon,Melting,0,Mon,6,2022
511,28-Jun-22,Hands,Male,25-34,Cut,0.0,Florida,Near Miss,Afternoon,Purchasing,0,Tue,6,2022
512,28-Jun-22,Trunk,Male,50+,Falling object,0.0,Florida,Medical Claim,Night,Administration,804,Tue,6,2022
513,28-Jun-22,Hands,Male,18-24,Vehicle,0.0,Texas,Medical Claim,Afternoon,Melting,706,Tue,6,2022

In [12]:
type(df)

pandas.core.frame.DataFrame

In [13]:
df.head()

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,1-Jan-20,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,$0,Wed,1,2020
1,3-Jan-20,NaN,Male,35-49,Vehicle,0.5,Alabama,Lost Time,Day,Fabrication,"$3,367",Fri,1,2020
2,3-Jan-20,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,$0,Fri,1,2020
3,4-Jan-20,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,$0,Sat,1,2020
4,7-Jan-20,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,$0,Tue,1,2020

In [16]:
df[df["Year"]==2020]

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,1-Jan-20,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,$0,Wed,1,2020
1,3-Jan-20,NaN,Male,35-49,Vehicle,0.5,Alabama,Lost Time,Day,Fabrication,"$3,367",Fri,1,2020
2,3-Jan-20,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,$0,Fri,1,2020
3,4-Jan-20,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,$0,Sat,1,2020
4,7-Jan-20,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,$0,Tue,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,27-Dec-20,Eye,Male,25-34,Falling object,0.0,Georgia,Medical Claim,Day,Security,$733,Sun,12,2020
217,27-Dec-20,Legs,Male,25-34,Burn,0.0,Illinois,First Aid,Day,Security,$265,Sun,12,2020
218,30-Dec-20,Trunk,Male,50+,Burn,0.0,Ohio,Medical Claim,Afternoon,Purchasing,"$5,000",Wed,12,2020
219,30-Dec-20,Trunk,Male,18-24,Fall,0.0,Montana,Medical Claim,Day,Finishing,"$4,366",Wed,12,2020
220,31-Dec-20,Abdomen,Male,25-34,Burn,2.0,Florida,Lost Time,Day,Finishing,"$3,060",Thu,12,2020

In [17]:
df.isnull()

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,False,False,False,False,False,False,False,False,False,False,False,False,False,False
510,False,False,False,False,False,False,False,False,False,False,False,False,False,False
511,False,False,False,False,False,False,False,False,False,False,False,False,False,False
512,False,False,False,False,False,False,False,False,False,False,False,False,False,False
513,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
df.isnull().sum()

Date                0
Injury Location    42
Gender              0
Age Group           0
Incident Type       0
Days Lost           0
Plant               0
Report Type         0
Shift               0
Department          0
Incident Cost       0
WkDay               0
Month               0
Year                0
dtype: int64

In [23]:
df.loc[3:7,{"Date","Injury Location","Year"}]

C:\Users\kbhunia\AppData\Local\Temp\ipykernel_25464\1323512253.py:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df.loc[3:7,{"Date","Injury Location","Year"}]

        Date Injury Location  Year
3   4-Jan-20            Legs  2020
4   7-Jan-20            Legs  2020
5  11-Jan-20             NaN  2020
6  11-Jan-20            Neck  2020
7  12-Jan-20            Feet  2020

In [25]:
df.loc[3:7,["Date","Injury Location","Year"]]

        Date Injury Location  Year
3   4-Jan-20            Legs  2020
4   7-Jan-20            Legs  2020
5  11-Jan-20             NaN  2020
6  11-Jan-20            Neck  2020
7  12-Jan-20            Feet  2020

In [41]:
df[df["Injury Location"]=="Eye"]

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
2,3-Jan-20,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,$0,Fri,1,2020
12,26-Jan-20,Eye,Male,35-49,Vehicle,0.0,Florida,Medical Claim,Day,Finishing,"$2,268",Sun,1,2020
13,27-Jan-20,Eye,Male,50+,Burn,0.0,Texas,Medical Claim,Day,Maintenance,$628,Mon,1,2020
14,27-Jan-20,Eye,Male,35-49,Burn,0.0,Georgia,First Aid,Night,Finishing,$77,Mon,1,2020
38,3-Mar-20,Eye,Male,35-49,Burn,0.0,Iowa,Near Miss,Afternoon,Shipping,$0,Tue,3,2020
40,6-Mar-20,Eye,Male,25-34,Burn,0.0,Ohio,Near Miss,Night,Shipping,$0,Fri,3,2020
46,20-Mar-20,Eye,Male,35-49,Lifting,0.0,Montana,Near Miss,Day,Security,$0,Fri,3,2020
56,13-Apr-20,Eye,Female,50+,Vehicle,4.5,Alabama,Lost Time,Night,Fabrication,"$1,152",Mon,4,2020
61,16-Apr-20,Eye,Male,50+,Burn,0.0,Iowa,First Aid,Afternoon,Painting,$155,Thu,4,2020
69,25-Apr-20,Eye,Female,50+,Equipment,0.0,Montana,Near Miss,Day,Purchasing,$0,Sat,4,2020
77,9-May-20,Eye,Male,35-49,Fall,0.0,Alabama,First Aid,Afternoon,Maintenance,$236,Sat,5,2020
91,26-May-20,Eye,Male,18-24,Lifting,0.0,Alabama,Medical Claim,Day,Administration,"$2,481",Tue,5,2020
99,12-Jun-20,Eye,Male,18-24,Slip/trip,0.0,California,Medical Claim,Day,Maintenance,"$3,269",Fri,6,2020
117,12-Jul-20,Eye,Male,18-24,Slip/trip,0.0,Montana,First Aid,Night,Melting,$118,Sun,7,2020
148,27-Aug-20,Eye,Male,18-24,Fall,0.0,Illinois,First Aid,Day,Administration,$395,Thu,8,2020
157,14-Sep-20,Eye,Male,35-49,Cut,0.0,Montana,Medical Claim,Night,Fabrication,"$1,136",Mon,9,2020
175,19-Oct-20,Eye,Male,25-34,Falling object,0.0,Texas,Near Miss,Day,Security,$0,Mon,10,2020
203,8-Dec-20,Eye,Male,18-24,Burn,0.0,Florida,First Aid,Afternoon,Painting,$115,Tue,12,2020
216,27-Dec-20,Eye,Male,25-34,Falling object,0.0,Georgia,Medical Claim,Day,Security,$733,Sun,12,2020
269,31-Mar-21,Eye,Female,18-24,Vehicle,5.0,Ohio,Lost Time,Night,Melting,"$1,993",Wed,3,2021
271,1-Apr-21,Eye,Male,25-34,Crush & Pinch,0.0,Illinois,Near Miss,Day,Shipping,$0,Thu,4,2021
279,15-Apr-21,Eye,Female,25-34,Burn,0.0,Illinois,Near Miss,Night,Administration,$0,Thu,4,2021
311,7-Jun-21,Eye,Male,50+,Fall,0.0,Illinois,First Aid,Day,Shipping,$107,Mon,6,2021
319,18-Jun-21,Eye,Male,35-49,Cut,1.5,Texas,Lost Time,Afternoon,Maintenance,"$1,698",Fri,6,2021
326,26-Jun-21,Eye,Male,18-24,Fall,0.0,Georgia,First Aid,Night,Finishing,$383,Sat,6,2021
327,27-Jun-21,Eye,Male,25-34,Falling object,4.5,Georgia,Lost Time,Day,Shipping,"$3,588",Sun,6,2021
359,23-Aug-21,Eye,Male,25-34,Burn,2.5,Georgia,Lost Time,Day,Security,"$3,817",Mon,8,2021
364,3-Sep-21,Eye,Male,25-34,Cut,0.0,Georgia,Medical Claim,Afternoon,Shipping,"$4,834",Fri,9,2021
369,15-Sep-21,Eye,Male,18-24,Equipment,0.0,Illinois,Near Miss,Night,Security,$0,Wed,9,2021
409,28-Nov-21,Eye,Female,50+,Fall,0.0,Alabama,First Aid,Day,Administration,$449,Sun,11,2021
436,21-Jan-22,Eye,Male,18-24,Burn,0.0,Alabama,Medical Claim,Afternoon,Purchasing,1277,Fri,1,2022
441,30-Jan-22,Eye,Female,35-49,Equipment,5.0,Ohio,Lost Time,Day,Shipping,1919,Sun,1,2022
456,23-Feb-22,Eye,Female,50+,Crush & Pinch,4.0,Iowa,Lost Time,Afternoon,Purchasing,1594,Wed,2,2022
470,26-Mar-22,Eye,Male,50+,Slip/trip,0.0,Texas,Medical Claim,Day,Shipping,4150,Sat,3,2022
471,28-Mar-22,Eye,Male,50+,Fall,0.0,Montana,First Aid,Night,Fabrication,259,Mon,3,2022
473,1-Apr-22,Eye,Male,18-24,Equipment,0.0,California,Medical Claim,Night,Painting,4130,Fri,4,2022
485,24-Apr-22,Eye,Male,18-24,Slip/trip,0.0,Iowa,Near Miss,Day,Shipping,0,Sun,4,2022
492,8-May-22,Eye,Male,25-34,Slip/trip,0.0,Montana,First Aid,Day,Shipping,277,Sun,5,2022
493,11-May-22,Eye,Male,50+,Fall,0.0,Iowa,First Aid,Afternoon,Security,189,Wed,5,2022
499,27-May-22,Eye,Male,18-24,Equipment,0.0,Georgia,First Aid,Afternoon,Administration,115,Fri,5,2022

In [44]:
df.loc[3:7,:]

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
3,4-Jan-20,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,$0,Sat,1,2020
4,7-Jan-20,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,$0,Tue,1,2020
5,11-Jan-20,NaN,Female,50+,Crush & Pinch,0.0,Georgia,First Aid,Afternoon,Security,$132,Sat,1,2020
6,11-Jan-20,Neck,Male,25-34,Crush & Pinch,3.5,Iowa,Lost Time,Day,Purchasing,"$4,872",Sat,1,2020
7,12-Jan-20,Feet,Male,35-49,Burn,1.5,California,Lost Time,Night,Administration,"$1,248",Sun,1,2020

In [54]:
df[df["Injury Location"].isnull()][["Date","Injury Location","Gender","Days Lost","Plant"]]

          Date Injury Location  Gender  Days Lost       Plant
1     3-Jan-20             NaN    Male        0.5     Alabama
5    11-Jan-20             NaN  Female        0.0     Georgia
8    15-Jan-20             NaN    Male        0.0     Florida
10   18-Jan-20             NaN  Female        0.0        Iowa
25   11-Feb-20             NaN    Male        0.0    Illinois
27   13-Feb-20             NaN    Male        4.5    Illinois
34   22-Feb-20             NaN    Male        0.0     Georgia
39    3-Mar-20             NaN    Male        2.5     Florida
53    6-Apr-20             NaN    Male        0.0    Illinois
55   12-Apr-20             NaN    Male        0.0        Ohio
83   17-May-20             NaN    Male        0.0        Ohio
111   6-Jul-20             NaN  Female        0.0        Ohio
118  13-Jul-20             NaN    Male        3.5        Ohio
124  26-Jul-20             NaN    Male        5.0       Texas
127  28-Jul-20             NaN    Male        2.0  California
129  30-Jul-20             NaN  Female        0.0        Ohio
152   5-Sep-20             NaN  Female        0.0       Texas
163  30-Sep-20             NaN    Male        0.0     Georgia
169  13-Oct-20             NaN    Male        2.5        Ohio
170  13-Oct-20             NaN    Male        1.5     Florida
173  16-Oct-20             NaN    Male        0.0  California
196  30-Nov-20             NaN    Male        0.0        Iowa
200   4-Dec-20             NaN    Male        0.0        Ohio
229  13-Jan-21             NaN    Male        1.5     Florida
236   2-Feb-21             NaN    Male        0.5    Illinois
259  14-Mar-21             NaN    Male        0.0    Illinois
273   6-Apr-21             NaN    Male        5.0    Illinois
275   9-Apr-21             NaN    Male        0.0       Texas
283  20-Apr-21             NaN    Male        0.0        Iowa
313   8-Jun-21             NaN    Male        0.0       Texas
349  10-Aug-21             NaN    Male        0.0     Florida
384  15-Oct-21             NaN  Female        4.0       Texas
405  22-Nov-21             NaN    Male        0.0     Georgia
421  29-Dec-21             NaN    Male        0.0    Illinois
425   4-Jan-22             NaN    Male        1.5        Iowa
426   8-Jan-22             NaN    Male        0.0       Texas
429  14-Jan-22             NaN    Male        0.0    Illinois
443   2-Feb-22             NaN    Male        1.5     Alabama
449   9-Feb-22             NaN    Male        0.0    Illinois
469  25-Mar-22             NaN    Male        0.5        Ohio
487  27-Apr-22             NaN    Male        0.0       Texas
497  23-May-22             NaN    Male        0.0     Florida

In [52]:
df[df["Injury Location"].isnull()]["Age Group"]

1      35-49
5        50+
8      18-24
10     35-49
25     25-34
27       50+
34     25-34
39       50+
53     18-24
55     25-34
83     35-49
111      50+
118      50+
124    25-34
127      50+
129    35-49
152    25-34
163    35-49
169    25-34
170    35-49
173      50+
196    25-34
200    25-34
229    25-34
236      50+
259    25-34
273      50+
275      50+
283      50+
313      50+
349      50+
384      50+
405    25-34
421      50+
425    25-34
426    25-34
429    35-49
443    25-34
449      50+
469    25-34
487      50+
497    18-24
Name: Age Group, dtype: object

In [60]:
df[(df["Shift"]=="Day") & (df["Gender"]=="Male")][["Date","Injury Location","Gender","Age Group"]]

          Date Injury Location Gender Age Group
1     3-Jan-20             NaN   Male     35-49
2     3-Jan-20             Eye   Male     18-24
4     7-Jan-20            Legs   Male     25-34
6    11-Jan-20            Neck   Male     25-34
12   26-Jan-20             Eye   Male     35-49
..         ...             ...    ...       ...
497  23-May-22             NaN   Male     18-24
503   3-Jun-22           Trunk   Male     18-24
505   5-Jun-22            Back   Male     25-34
506   7-Jun-22         Abdomen   Male     25-34
508  25-Jun-22            Feet   Male       50+

[157 rows x 4 columns]

In [61]:
df

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
0,1-Jan-20,Multiple,Male,25-34,Burn,0.0,Iowa,Near Miss,Afternoon,Painting,$0,Wed,1,2020
1,3-Jan-20,NaN,Male,35-49,Vehicle,0.5,Alabama,Lost Time,Day,Fabrication,"$3,367",Fri,1,2020
2,3-Jan-20,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,$0,Fri,1,2020
3,4-Jan-20,Legs,Female,50+,Falling object,0.0,Iowa,Near Miss,Day,Painting,$0,Sat,1,2020
4,7-Jan-20,Legs,Male,25-34,Lifting,0.0,Ohio,Near Miss,Day,Painting,$0,Tue,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,26-Jun-22,Head,Female,25-34,Crush & Pinch,0.0,California,First Aid,Night,Administration,77,Sun,6,2022
510,27-Jun-22,Hands,Male,25-34,Lifting,0.0,Florida,Near Miss,Afternoon,Melting,0,Mon,6,2022
511,28-Jun-22,Hands,Male,25-34,Cut,0.0,Florida,Near Miss,Afternoon,Purchasing,0,Tue,6,2022
512,28-Jun-22,Trunk,Male,50+,Falling object,0.0,Florida,Medical Claim,Night,Administration,804,Tue,6,2022
513,28-Jun-22,Hands,Male,18-24,Vehicle,0.0,Texas,Medical Claim,Afternoon,Melting,706,Tue,6,2022

In [72]:
df[(df["Injury Location"]=="Eye")]

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
2,3-Jan-20,Eye,Male,18-24,Cut,0.0,Georgia,Near Miss,Day,Administration,$0,Fri,1,2020
12,26-Jan-20,Eye,Male,35-49,Vehicle,0.0,Florida,Medical Claim,Day,Finishing,"$2,268",Sun,1,2020
13,27-Jan-20,Eye,Male,50+,Burn,0.0,Texas,Medical Claim,Day,Maintenance,$628,Mon,1,2020
14,27-Jan-20,Eye,Male,35-49,Burn,0.0,Georgia,First Aid,Night,Finishing,$77,Mon,1,2020
38,3-Mar-20,Eye,Male,35-49,Burn,0.0,Iowa,Near Miss,Afternoon,Shipping,$0,Tue,3,2020
40,6-Mar-20,Eye,Male,25-34,Burn,0.0,Ohio,Near Miss,Night,Shipping,$0,Fri,3,2020
46,20-Mar-20,Eye,Male,35-49,Lifting,0.0,Montana,Near Miss,Day,Security,$0,Fri,3,2020
56,13-Apr-20,Eye,Female,50+,Vehicle,4.5,Alabama,Lost Time,Night,Fabrication,"$1,152",Mon,4,2020
61,16-Apr-20,Eye,Male,50+,Burn,0.0,Iowa,First Aid,Afternoon,Painting,$155,Thu,4,2020
69,25-Apr-20,Eye,Female,50+,Equipment,0.0,Montana,Near Miss,Day,Purchasing,$0,Sat,4,2020
77,9-May-20,Eye,Male,35-49,Fall,0.0,Alabama,First Aid,Afternoon,Maintenance,$236,Sat,5,2020
91,26-May-20,Eye,Male,18-24,Lifting,0.0,Alabama,Medical Claim,Day,Administration,"$2,481",Tue,5,2020
99,12-Jun-20,Eye,Male,18-24,Slip/trip,0.0,California,Medical Claim,Day,Maintenance,"$3,269",Fri,6,2020
117,12-Jul-20,Eye,Male,18-24,Slip/trip,0.0,Montana,First Aid,Night,Melting,$118,Sun,7,2020
148,27-Aug-20,Eye,Male,18-24,Fall,0.0,Illinois,First Aid,Day,Administration,$395,Thu,8,2020
157,14-Sep-20,Eye,Male,35-49,Cut,0.0,Montana,Medical Claim,Night,Fabrication,"$1,136",Mon,9,2020
175,19-Oct-20,Eye,Male,25-34,Falling object,0.0,Texas,Near Miss,Day,Security,$0,Mon,10,2020
203,8-Dec-20,Eye,Male,18-24,Burn,0.0,Florida,First Aid,Afternoon,Painting,$115,Tue,12,2020
216,27-Dec-20,Eye,Male,25-34,Falling object,0.0,Georgia,Medical Claim,Day,Security,$733,Sun,12,2020
269,31-Mar-21,Eye,Female,18-24,Vehicle,5.0,Ohio,Lost Time,Night,Melting,"$1,993",Wed,3,2021
271,1-Apr-21,Eye,Male,25-34,Crush & Pinch,0.0,Illinois,Near Miss,Day,Shipping,$0,Thu,4,2021
279,15-Apr-21,Eye,Female,25-34,Burn,0.0,Illinois,Near Miss,Night,Administration,$0,Thu,4,2021
311,7-Jun-21,Eye,Male,50+,Fall,0.0,Illinois,First Aid,Day,Shipping,$107,Mon,6,2021
319,18-Jun-21,Eye,Male,35-49,Cut,1.5,Texas,Lost Time,Afternoon,Maintenance,"$1,698",Fri,6,2021
326,26-Jun-21,Eye,Male,18-24,Fall,0.0,Georgia,First Aid,Night,Finishing,$383,Sat,6,2021
327,27-Jun-21,Eye,Male,25-34,Falling object,4.5,Georgia,Lost Time,Day,Shipping,"$3,588",Sun,6,2021
359,23-Aug-21,Eye,Male,25-34,Burn,2.5,Georgia,Lost Time,Day,Security,"$3,817",Mon,8,2021
364,3-Sep-21,Eye,Male,25-34,Cut,0.0,Georgia,Medical Claim,Afternoon,Shipping,"$4,834",Fri,9,2021
369,15-Sep-21,Eye,Male,18-24,Equipment,0.0,Illinois,Near Miss,Night,Security,$0,Wed,9,2021
409,28-Nov-21,Eye,Female,50+,Fall,0.0,Alabama,First Aid,Day,Administration,$449,Sun,11,2021
436,21-Jan-22,Eye,Male,18-24,Burn,0.0,Alabama,Medical Claim,Afternoon,Purchasing,1277,Fri,1,2022
441,30-Jan-22,Eye,Female,35-49,Equipment,5.0,Ohio,Lost Time,Day,Shipping,1919,Sun,1,2022
456,23-Feb-22,Eye,Female,50+,Crush & Pinch,4.0,Iowa,Lost Time,Afternoon,Purchasing,1594,Wed,2,2022
470,26-Mar-22,Eye,Male,50+,Slip/trip,0.0,Texas,Medical Claim,Day,Shipping,4150,Sat,3,2022
471,28-Mar-22,Eye,Male,50+,Fall,0.0,Montana,First Aid,Night,Fabrication,259,Mon,3,2022
473,1-Apr-22,Eye,Male,18-24,Equipment,0.0,California,Medical Claim,Night,Painting,4130,Fri,4,2022
485,24-Apr-22,Eye,Male,18-24,Slip/trip,0.0,Iowa,Near Miss,Day,Shipping,0,Sun,4,2022
492,8-May-22,Eye,Male,25-34,Slip/trip,0.0,Montana,First Aid,Day,Shipping,277,Sun,5,2022
493,11-May-22,Eye,Male,50+,Fall,0.0,Iowa,First Aid,Afternoon,Security,189,Wed,5,2022
499,27-May-22,Eye,Male,18-24,Equipment,0.0,Georgia,First Aid,Afternoon,Administration,115,Fri,5,2022

In [75]:
df[(df["WkDay"]=="Sun")]

,Date,Injury Location,Gender,Age Group,Incident Type,Days Lost,Plant,Report Type,Shift,Department,Incident Cost,WkDay,Month,Year
7,12-Jan-20,Feet,Male,35-49,Burn,1.5,California,Lost Time,Night,Administration,"$1,248",Sun,1,2020
12,26-Jan-20,Eye,Male,35-49,Vehicle,0.0,Florida,Medical Claim,Day,Finishing,"$2,268",Sun,1,2020
21,9-Feb-20,Feet,Male,35-49,Crush & Pinch,0.0,Montana,First Aid,Afternoon,Melting,$180,Sun,2,2020
22,9-Feb-20,Head,Male,25-34,Equipment,4.5,Florida,Lost Time,Afternoon,Shipping,"$3,784",Sun,2,2020
30,16-Feb-20,Abdomen,Male,50+,Slip/trip,0.0,California,First Aid,Day,Fabrication,$207,Sun,2,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,24-Apr-22,Abdomen,Male,25-34,Crush & Pinch,0.0,Alabama,Medical Claim,Afternoon,Fabrication,1848,Sun,4,2022
485,24-Apr-22,Eye,Male,18-24,Slip/trip,0.0,Iowa,Near Miss,Day,Shipping,0,Sun,4,2022
492,8-May-22,Eye,Male,25-34,Slip/trip,0.0,Montana,First Aid,Day,Shipping,277,Sun,5,2022
505,5-Jun-22,Back,Male,25-34,Slip/trip,0.0,Iowa,Near Miss,Day,Purchasing,0,Sun,6,2022
509,26-Jun-22,Head,Female,25-34,Crush & Pinch,0.0,California,First Aid,Night,Administration,77,Sun,6,2022